<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="3" passed="1" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2020-01-22T11:51:19 IST" name="Suite" finished-at="2020-01-22T11:51:19 IST" duration-ms="68">
    <groups>
    </groups>
    <test started-at="2020-01-22T11:51:19 IST" name="Test" finished-at="2020-01-22T11:51:19 IST" duration-ms="68">
      <class name="test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations">
        <test-method is-config="true" signature="setUp()[pri:0, instance:test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations@1677d1]" started-at="2020-01-22T11:51:19 IST" name="setUp" finished-at="2020-01-22T11:51:19 IST" duration-ms="195" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="test()[pri:0, instance:test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations@1677d1]" started-at="2020-01-22T11:51:19 IST" name="test" finished-at="2020-01-22T11:51:19 IST" duration-ms="12" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations@1677d1]" started-at="2020-01-22T11:51:19 IST" name="afterMethod" finished-at="2020-01-22T11:51:19 IST" duration-ms="2" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test status=SUCCESS method=SucessFunctionalValidations.test()[pri:0, instance:test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations@1677d1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method signature="test1()[pri:0, instance:test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations@1677d1]" started-at="2020-01-22T11:51:19 IST" name="test1" finished-at="2020-01-22T11:51:19 IST" duration-ms="2" status="SKIP">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Exception raised]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Exception raised
at test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations.test1(SucessFunctionalValidations.java:41)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method signature="test2()[pri:0, instance:test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations@1677d1]" started-at="2020-01-22T11:51:19 IST" name="test2" finished-at="2020-01-22T11:51:19 IST" duration-ms="10" status="FAIL">
          <exception class="junit.framework.AssertionFailedError">
            <message>
              <![CDATA[method failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[junit.framework.AssertionFailedError: method failed
at junit.framework.Assert.fail(Assert.java:47)
at test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations.test2(SucessFunctionalValidations.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- junit.framework.AssertionFailedError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations@1677d1]" started-at="2020-01-22T11:51:19 IST" name="afterMethod" finished-at="2020-01-22T11:51:19 IST" duration-ms="0" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test1 status=SKIP method=SucessFunctionalValidations.test1()[pri:0, instance:test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations@1677d1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations@1677d1]" started-at="2020-01-22T11:51:19 IST" name="afterMethod" finished-at="2020-01-22T11:51:19 IST" duration-ms="1" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test2 status=FAILURE method=SucessFunctionalValidations.test2()[pri:0, instance:test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations@1677d1] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="afterClass()[pri:0, instance:test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations@1677d1]" started-at="2020-01-22T11:51:19 IST" name="afterClass" finished-at="2020-01-22T11:51:20 IST" duration-ms="371" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
      </class> <!-- test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
