<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Love" failures="1" tests="3" name="Test" time="0.068" errors="0" timestamp="2020-01-22T11:51:19 IST">
  <testcase classname="test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations" name="test" time="0.012"/>
  <testcase classname="test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations" name="test1" time="0.002">
    <skipped/>
  </testcase> <!-- test1 -->
  <testcase classname="test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations" name="test2" time="0.01">
    <failure type="junit.framework.AssertionFailedError" message="method failed">
      <![CDATA[junit.framework.AssertionFailedError: method failed
at junit.framework.Assert.fail(Assert.java:47)
at test_cases.module_001.api_aaa.functional_validations.SucessFunctionalValidations.test2(SucessFunctionalValidations.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1507)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
</testsuite> <!-- Test -->
